<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="114971" started-at="2015-01-27T17:07:23Z" finished-at="2015-01-27T17:09:18Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="114971" started-at="2015-01-27T17:07:23Z" finished-at="2015-01-27T17:09:18Z">
      <class name="test.java.FunctionalTests">
        <test-method status="PASS" signature="setUp()[pri:0, instance:test.java.FunctionalTests@402dae86]" name="setUp" is-config="true" duration-ms="37254" started-at="2015-01-27T18:07:23Z" finished-at="2015-01-27T18:08:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="firstTest()[pri:0, instance:test.java.FunctionalTests@402dae86]" name="firstTest" duration-ms="30642" started-at="2015-01-27T18:08:01Z" finished-at="2015-01-27T18:08:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- firstTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:test.java.FunctionalTests@402dae86]" name="tearDown" is-config="true" duration-ms="1109" started-at="2015-01-27T18:08:31Z" finished-at="2015-01-27T18:08:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:test.java.FunctionalTests@402dae86]" name="setUp" is-config="true" duration-ms="23960" started-at="2015-01-27T18:08:32Z" finished-at="2015-01-27T18:08:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="secondTest()[pri:0, instance:test.java.FunctionalTests@402dae86]" name="secondTest" duration-ms="15604" started-at="2015-01-27T18:08:56Z" finished-at="2015-01-27T18:09:12Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at test.java.FunctionalTests.secondTest(FunctionalTests.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- secondTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:test.java.FunctionalTests@402dae86]" name="tearDown" is-config="true" duration-ms="6301" started-at="2015-01-27T18:09:12Z" finished-at="2015-01-27T18:09:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- test.java.FunctionalTests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
